---

# madeb #

- name: /etc/apt/sources.list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: 0644
    
- name: Depot backports
  lineinfile:
    path: /etc/apt/sources.list
    #~ regexp: '^deb http://ftp.fr.debian.org/debian/ bullseye-backports main contrib non-free'
    #~ line: 'deb http://ftp.fr.debian.org/debian/ bullseye-backports main contrib non-free'
    regexp: '^deb http://deb.debian.org/debian/ bullseye-backports main contrib non-free'
    line: 'deb http://deb.debian.org/debian/ bullseye-backports main contrib non-free'
    state: present
